## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Cidreira,BR,2021-11-12 19:27:34,-30.1811,-50.2056,66.72,63,94,16.17,overcast clouds
1,1,Albany,US,2021-11-12 19:27:34,42.6001,-73.9662,57.27,85,100,3.00,overcast clouds
2,2,Camacha,PT,2021-11-12 19:27:35,33.0833,-16.3333,63.82,63,40,8.05,scattered clouds
3,3,Cape Town,ZA,2021-11-12 19:25:06,-33.9258,18.4232,66.11,84,20,1.99,few clouds
4,4,Qaanaaq,GL,2021-11-12 19:27:35,77.4840,-69.3632,-6.29,58,0,8.70,clear sky

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 95

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
6,6,Kudahuvadhoo,MV,2021-11-12 19:27:36,2.6708,72.8944,82.69,76,13,19.39,few clouds
7,7,San Andres,CO,2021-11-12 19:27:36,12.5847,-81.7006,87.82,66,20,12.66,few clouds
12,12,Isangel,VU,2021-11-12 19:22:47,-19.5500,169.2667,76.77,84,3,4.92,clear sky
14,14,Lorengau,PG,2021-11-12 19:27:38,-2.0226,147.2712,80.91,80,98,1.74,overcast clouds
15,15,Vila Do Maio,CV,2021-11-12 19:27:39,15.1333,-23.2167,77.79,73,24,12.77,few clouds
23,23,Cabo San Lucas,MX,2021-11-12 19:27:41,22.8909,-109.9124,87.10,64,1,1.01,clear sky
26,26,Avarua,CK,2021-11-12 19:27:42,-21.2078,-159.7750,78.85,78,20,14.97,few clouds
28,28,Acari,PE,2021-11-12 19:23:14,-15.4311,-74.6158,76.08,54,92,11.39,overcast clouds
29,29,Tarpon Springs,US,2021-11-12 19:27:43,28.1461,-82.7568,80.29,72,1,3.00,clear sky
41,41,Ahuimanu,US,2021-11-12 19:27:47,21.4447,-157.8378,81.79,62,1,0.00,clear sky

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                199
City                   199
Country                199
Date                   199
Lat                    199
Lng                    199
Max Temp               199
Humidity               199
Cloudiness             199
Wind Speed             199
Current Description    199
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
6,Kudahuvadhoo,MV,82.69,few clouds,2.6708,72.8944,
7,San Andres,CO,87.82,few clouds,12.5847,-81.7006,
12,Isangel,VU,76.77,clear sky,-19.5500,169.2667,
14,Lorengau,PG,80.91,overcast clouds,-2.0226,147.2712,
15,Vila Do Maio,CV,77.79,few clouds,15.1333,-23.2167,
23,Cabo San Lucas,MX,87.10,clear sky,22.8909,-109.9124,
26,Avarua,CK,78.85,few clouds,-21.2078,-159.7750,
28,Acari,PE,76.08,overcast clouds,-15.4311,-74.6158,
29,Tarpon Springs,US,80.29,clear sky,28.1461,-82.7568,
41,Ahuimanu,US,81.79,clear sky,21.4447,-157.8378,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [11]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.count()

City                   199
Country                199
Max Temp               199
Current Description    199
Lat                    199
Lng                    199
Hotel Name             199
dtype: int64

In [12]:
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
6,Kudahuvadhoo,MV,82.69,few clouds,2.6708,72.8944,Niyama Private Islands Maldives
7,San Andres,CO,87.82,few clouds,12.5847,-81.7006,Hotel Arena Blanca
12,Isangel,VU,76.77,clear sky,-19.5500,169.2667,Tanna Lodge
14,Lorengau,PG,80.91,overcast clouds,-2.0226,147.2712,Lorengau Harbourside Hotel
15,Vila Do Maio,CV,77.79,few clouds,15.1333,-23.2167,Hotel Marilu
23,Cabo San Lucas,MX,87.10,clear sky,22.8909,-109.9124,Hotel Tesoro Los Cabos
26,Avarua,CK,78.85,few clouds,-21.2078,-159.7750,Paradise Inn
28,Acari,PE,76.08,overcast clouds,-15.4311,-74.6158,HOSPEDAJE XIMENA
29,Tarpon Springs,US,80.29,clear sky,28.1461,-82.7568,"Innisbrook, A Salamander Golf and Spa Resort"
41,Ahuimanu,US,81.79,clear sky,21.4447,-157.8378,Paradise Bay Resort

In [15]:
# 8a. Create the output File (CSV)
output_data_file = "../Vacation_Search/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [17]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [18]:
# 11a. Add a marker layer for each city to the map. 
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))